### PR TITLE
[Feature] Implement backend for user service

### PR DESCRIPTION
**Pull request by Raveesha-Induwara**
# [Feature] Implement backend for user service

---

## **Description**
This PR introduces the backend implementation for all features in the user-service, auth-service, order-service, product-service, cart-service, inventory-service and payment-service modules. The changes include:

- API endpoints for all services (CRUD operations).
- Integration with authentication and authorization mechanisms.
- Logging and exception handling enhancements.

---

## **Type of Change**
- [x] New feature (non-breaking change that adds functionality)
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements or additions to documentation)
- [ ] Other (please specify):

---

## **How Has This Been Tested?**
- **Unit Tests**: All new service methods have associated unit tests with high coverage.

---

## **Checklist**
- [x] Code is well-documented and follows coding guidelines.
- [ ] Tests are written and passing for new functionality.
- [ ] Related documentation is updated or added.
- [x] All merge conflicts resolved.

---

## **Additional Notes**
- No database schema changes are included in this PR.
- Requires coordination with the frontend team for endpoint integration.

### CODE REVIEW

**Comment by AvishkaWPA** [comment]
payment service checked. no issues

**Review by AvishkaWPA — APPROVED** [review]
Payment service checked. no issues

**Comment by WAJAMASARA** [comment]
feat: Review and merge Order and Product Service updates  

- Verified the functionality of the Order and Product services.  
- Ensured there are no issues or bugs present in the services.  
- All tests passed successfully.

**Comment by WAJAMASARA** [comment]
feat: Review and merge Order and Product Service updates  

- Verified the functionality of the Order and Product services.  
- Ensured there are no issues or bugs present in the services.  
- All tests passed successfully.

**Pull request merged**
